# Generated by Django 3.0.5 on 2020-05-02 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameimage',
            old_name='candy',
            new_name='game',
        ),
    ]
